CREATE DATABASE LOST_DOG_DB;

USE LOST_DOG_DB;
CREATE TABLE CAES (
ID_CAO INT NOT NULL AUTO_INCREMENT, 
NOME VARCHAR(20) NOT NULL, 
ID_RACA INT NOT NULL, 
PRIMARY KEY (ID_CAO)
);

USE LOST_DOG_DB;
CREATE TABLE RACAS (
ID_RACA INT NOT NULL AUTO_INCREMENT,
RACA VARCHAR(20) NOT NULL,
PRIMARY KEY (ID_RACA)
);

INSERT INTO RACAS (ID_RACA, RACA) VALUES (1, 'Rottweiler'), (2, 'Bulldog'), (3, 'Pug'), (4, 'Pastor Alemão'), (5, 'Labrador');

ALTER TABLE CAES ADD FOREIGN KEY (ID_RACA) REFERENCES RACAS(ID_RACA);

USE LOST_DOG_DB;
CREATE TABLE USUARIOS (
ID_USUARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
TELEFONE VARCHAR(11) NULL,
EMAIL VARCHAR(30) NULL,
HASH VARCHAR(255) NULL,
AREA VARCHAR(40) NULL,
CIDADE VARCHAR(30) NULL,
PRIMARY KEY (ID_USUARIO)
);

INSERT INTO USUARIOS (NOME) VALUES ('Usuário Anônimo');

USE LOST_DOG_DB;
CREATE TABLE STATUS (
ID_STATUS INT NOT NULL AUTO_INCREMENT,
SITUACAO VARCHAR(50),
PRIMARY KEY (ID_STATUS)
);

INSERT INTO STATUS (SITUACAO) VALUES 
('Perdido'),
('Encontrado na rua'),
('Encontrado pelo dono'),
('Desativado');

USE LOST_DOG_DB;
CREATE TABLE POSTAGENS (
ID_POST INT NOT NULL AUTO_INCREMENT,
AREA VARCHAR(40) NULL,
CIDADE VARCHAR(30) NULL,
DATA DATETIME NOT NULL,
TELEFONE VARCHAR(11) NULL,
EMAIL VARCHAR(30) NULL,
ID_CAO INT NOT NULL,
ID_USUARIO INT NOT NULL,
ID_STATUS INT NOT NULL,
FOREIGN KEY (ID_CAO) REFERENCES CAES(ID_CAO),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID_STATUS),
PRIMARY KEY (ID_POST)
);

USE LOST_DOG_DB;
CREATE TABLE IMAGENS (
ID_IMAGEM INT NOT NULL AUTO_INCREMENT,
PATH VARCHAR(255),
ID_POST INT NOT NULL,
FOREIGN KEY (ID_POST) REFERENCES POSTAGENS(ID_POST),
PRIMARY KEY (ID_IMAGEM)
);

-- SELECT * FROM CAES;
-- SELECT * FROM USUARIOS;
-- SELECT * FROM RACAS;
-- SELECT * FROM POSTAGENS;
-- SELECT * FROM IMAGENS;
-- SELECT * FROM STATUS;